
class algofi_pool_strings:
    # user variables
    admin = "a"
    asset1_id = "a1"
    asset_1_to_asset_2_exchange = "e"
    asset2_id = "a2"
    asset1_reserve = "a1r"
    asset2_reserve = "a2r"
    balance_1 = "b1"
    balance_2 = "b2"
    burn_asset1_out = "ba1o"
    burn_asset2_out = "ba2o"
    contract_update_delay = "cud"
    contract_update_time = "cut"
    cumsum_fees_asset1 = "cf1"
    cumsum_fees_asset2 = "cf2"
    cumsum_time_weighted_asset1_to_asset2_price = "ct12"
    cumsum_time_weighted_asset2_to_asset1_price = "ct21"
    cumsum_volume_asset1 = "cv1"
    cumsum_volume_asset2 = "cv2"
    cumsum_volume_weighted_asset1_to_asset2_price = "cv12"
    cumsum_volume_weighted_asset2_to_asset1_price = "cv21"
    flash_loan = "fl"
    flash_loan_fee = "flf"
    increase_contract_update_delay = "icud"
    latest_time = "lt"
    lp_circulation = "lc"
    lp_id = "l"
    manager = "m"
    max_flash_loan_ratio = "mflr"
    opt_into_assets = "o"
    pool = "p"
    redeem_pool_asset1_residual = "rpa1r"
    redeem_pool_asset2_residual = "rpa2r"
    redeem_swap_residual = "rsr"
    remove_reserves = "rr"
    reserve_factor = "rf"
    schedule_contract_update = "scu"
    swap_exact_for = "sef"
    swap_for_exact = "sfe"
    initialized = "i"
    initialize_pool = "ip"
    amplification_factor = "af"


class algofi_manager_strings:
    admin = "a"
    contract_update_delay = "cud"
    contract_update_time = "cut"
    flash_loan_fee = "flf"
    increase_contract_update_delay = "icud"
    initialize_pool = "ip"
    max_flash_loan_ratio = "mflr"
    pool_hash_prefix = "ph_"
    registered_asset_1_id = "a1"
    registered_asset_2_id = "a2"
    registered_pool_id = "p"
    reserve_factor = "rf"
    schedule_contract_update = "scu"
    set_flash_loan_fee = "sflf"
    set_reserve_factor = "srf"
    set_max_flash_loan_ratio = "smflr"
    set_validator = "sv"
    validator_index="vi"